display:
  background:
    path: /usr/share/thermalright-lcd-control/themes/backgrounds/a004.png
    type: image
  date:
    color: '#FFFFFFFF'
    enabled: false
    font_size: 24
    position:
      x: 15
      y: 3
    text: ''
  foreground:
    alpha: 0.8
    enabled: true
    path: /usr/share/thermalright-lcd-control/themes/foregrounds/{resolution}/008a.png
    position:
      x: 0
      y: 0
  metrics:
    configs:
    - color: '#FFFFFFFF'
      enabled: true
      font_size: 24
      format_string: '{label}{value}{unit}'
      label: ''
      name: cpu_temperature
      position:
        x: 37
        y: 103
      unit: °C
    - color: '#FFFFFFFF'
      enabled: true
      font_size: 24
      format_string: '{label}{value}{unit}'
      label: ''
      name: gpu_temperature
      position:
        x: 259
        y: 103
      unit: °C
    - color: '#FFFFFFFF'
      enabled: true
      font_size: 24
      format_string: '{label}{value}{unit}'
      label: ''
      name: cpu_frequency
      position:
        x: 89
        y: 33
      unit: MHZ
    - color: '#FFFFFFFF'
      enabled: true
      font_size: 24
      format_string: '{label}{value}{unit}'
      label: ''
      name: gpu_frequency
      position:
        x: 90
        y: 171
      unit: MHZ
    enabled: true
  time:
    color: '#FFFFFFFF'
    enabled: true
    font_size: 24
    position:
      x: 137
      y: 103
    text: ''
