# SPDX-License-Identifier: Apache-2.0
# Copyright Â© 2025 Rejeb Ben Rejeb

paths:
  themes_dir: "./resources/themes/presets"
  backgrounds_dir: "./resources/themes/backgrounds"
  foregrounds_dir: "./resources/themes/foregrounds"
  service_config: "./resources/config"
window:
  default_width: 1200
  default_height: 700
  min_width: 800
  min_height: 600

supported_formats:
  images: [ '.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp' ]
  videos: [ '.mp4', '.avi', '.mkv', '.mov', '.webm', '.flv', '.wmv', '.m4v' ]
  gifs: [ '.gif' ]

supported_devices:
  - vid: "0x0416"
    pid: "0x5302"
    width: 320
    height: 240

  - vid: "0x0418"
    pid: "0x5304"
    width: 480
    height: 480

  - vid: "87ad"
    pid: "70db"
    width: 320
    height: 320